-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS childhood.attendance
(
    id serial NOT NULL,
    absence_date date NOT NULL,
    child_id integer NOT NULL,
    reason text COLLATE pg_catalog."default",
    CONSTRAINT attendance_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS childhood.child_parent
(
    child_id integer NOT NULL,
    parent_id integer NOT NULL,
    CONSTRAINT child_parent_pkey PRIMARY KEY (child_id, parent_id)
);

CREATE TABLE IF NOT EXISTS childhood.children
(
    id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birth_date date,
    group_id integer,
    CONSTRAINT children_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS childhood.educators
(
    id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    experience integer,
    hire_date date,
    CONSTRAINT educators_pkey PRIMARY KEY (id),
    CONSTRAINT educator_name_unique UNIQUE (full_name)
);

CREATE TABLE IF NOT EXISTS childhood.group_educator
(
    group_id integer NOT NULL,
    educator_id integer NOT NULL,
    CONSTRAINT group_educator_pkey PRIMARY KEY (group_id, educator_id)
);

CREATE TABLE IF NOT EXISTS childhood.groups
(
    id serial NOT NULL,
    group_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (id),
    CONSTRAINT group_number_unique UNIQUE (group_number)
);

CREATE TABLE IF NOT EXISTS childhood.parents
(
    id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT parents_pkey PRIMARY KEY (id),
    CONSTRAINT parent_name_unique UNIQUE (full_name)
);

CREATE TABLE IF NOT EXISTS childhood.payments
(
    id serial NOT NULL,
    amount numeric(10, 2) NOT NULL,
    period character varying(7) COLLATE pg_catalog."default" NOT NULL,
    child_id integer NOT NULL,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS childhood.attendance
    ADD CONSTRAINT attendance_child_id_fkey FOREIGN KEY (child_id)
    REFERENCES childhood.children (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS childhood.child_parent
    ADD CONSTRAINT child_parent_child_id_fkey FOREIGN KEY (child_id)
    REFERENCES childhood.children (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS childhood.child_parent
    ADD CONSTRAINT child_parent_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES childhood.parents (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS childhood.children
    ADD CONSTRAINT children_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES childhood.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS childhood.group_educator
    ADD CONSTRAINT group_educator_educator_id_fkey FOREIGN KEY (educator_id)
    REFERENCES childhood.educators (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS childhood.group_educator
    ADD CONSTRAINT group_educator_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES childhood.groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS childhood.payments
    ADD CONSTRAINT payments_child_id_fkey FOREIGN KEY (child_id)
    REFERENCES childhood.children (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;